# Generated by Django 3.1.2 on 2020-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201016_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaleventbooking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='youtheventbooking',
            name='full_name',
        ),
        migrations.AddField(
            model_name='generaleventbooking',
            name='first_name',
            field=models.CharField(default='', help_text='Your first name.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaleventbooking',
            name='last_name',
            field=models.CharField(default='', help_text='Your last name.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtheventbooking',
            name='first_name',
            field=models.CharField(default='', help_text='Your first name.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtheventbooking',
            name='last_name',
            field=models.CharField(default='', help_text='Your last name.', max_length=50),
            preserve_default=False,
        ),
    ]
